version: '3'

services: 
  apache:
    build: ./apache
    ports: 
      - 80:80
    environment: 
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks: 
      - frontend-network
      - backend-network

  mysql:
    image: mysql:8.0
    #ports:
    #  - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - LANG=C.UTF-8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
    networks: 
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on: 
      - mysql 
    networks: 
      - frontend-network
      - backend-network

volumes:
  mysql_data:

networks:
  frontend-network:
  backend-network: