version: '3'

services: 
  apache:
    build: ./apache
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks: 
      - frontend-network
      - backend-network

  mysql:
    image: mysql:8.0
    #ports:
    #  - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
    networks: 
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on: 
      - mysql 
    networks: 
      - frontend-network
      - backend-network

volumes:
  mysql_data:

networks:
  frontend-network:
  backend-network: