version: '3'

services:
  moodle:
    image: bitnami/moodle
    ports:
      - 80:80
    environment: 
      - MARIADB_HOST=mariadb
      - MOODLE_DATABASE_NAME=moodle_database   
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
    volumes:
      - moodle_data:/bitnami
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moodle_database
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=moodle_password
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1

volumes:
  moodle_data:
  mariadb_data: