version: '3'

services: 
  apache:
    image: php:7.2-apache
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7.28
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: